openapi: "3.0.0"
info:
  version: 1.0.0
  title: Ecampus Finder API
  description: Uma API para realizar buscas sobre turmas da 2ª solicitação de matrícula da UFAM
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /v1
paths:
  /search:
    get:
      description: Buscar por disciplinas, turmas ou cursos
      operationId: searchClasses
      parameters:
        - name: query
          in: query
          required: true
          description: Consulta para fazer
          example: "Fotografia 16:00"
          schema:
            type: string
        - name: limit
          in: query
          required: true
          description: Número máximo de resultados para retornar
          example: 10
          schema:
            type: integer
            maximum: 20
            minimum: 1
        - name: offset
          in: query
          description: Número de resultados que serão pulados na busca
          example: 60
          schema:
            type: integer
            maximum: 10000
            minimum: 0
        - name: sort
          in: query
          description: Forma de ordenação
          example: asc:concorrencia
          schema:
            type: string
            pattern: ^(asc|desc):(concorrencia|cursoNome|disciplinaNome)$
        - name: filter
          in: query
          description: Dias e horários para filtrar
          schema:
            type: object
            required: 
            - startTimestampsMin
            - endTimestampsMin
            - days
            properties:
              startTimestampsMin:
                example: [500, 950]
                type: array
                items:
                  # Pode haver no máximo 24 horários disponíveis para seleção em um único dia. 
                  # Portanto, em uma semana há no máximo 24 * 7 = 168 horários.
                  maxItems: 168
                  type: integer
                  minimum: 1
                  maximum: 1440
              endTimestampsMin:
                example: [600, 1000]
                type: array
                items:
                  maxItems: 168 
                  type: integer
                  minimum: 1
                  maximum: 1440 
              days:
                type: array
                example: ["seg", "ter"]
                items:
                  type: string
                  pattern: ^(seg|ter|qua|qui|sex|sab)$
                  maxItems: 168

      responses:
        '200':
          description: resultados da busca
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hit'
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Hit:
      required:
        - codigo
        - curso
        - disciplina
        - horarios
      properties:
        codigo:
          type: string
          example: "1"
        curso:
          type: object
          properties:
            nome:
              type: string
              example: "Engenharia da Computação (Diurno)"
            codigo:
              type: string
              example: "FO05"
        disciplina:
          type: object
          properties:
            nome:
              type: string
              example: "EQUACÕES DIFERENCIAIS ORDINÁRIAS"
            codigo:
              type: string
              example: "IEM141"
        horarios:
          type: array
          items:
            type: object
            properties:
              dias:
                type: array
                items:
                  type: string
                  example: "Terça-feira"
              inicio:
                type: string
                example: "08:00"
              termino:
                type: string
                example: "10:00"
            
        concorrencia:
          type: number
          format: float
          description: relação de candidatos por vaga
          example: 0.75
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
