openapi: "3.0.0"
info:
  version: 1.0.0
  title: Ecampus Finder API
  description: Uma API para realizar buscas sobre turmas da 2ª solicitação de matrícula da UFAM
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /search:
    post:
      description: Buscar por disciplinas, turmas ou cursos
      operationId: searchClasses
      parameters:
        - name: query
          in: query
          required: true
          description: Consulta para fazer
          example: "Fotografia 16:00"
          schema:
            type: string
            minLength: 1
            maxLength: 128
        - name: limit
          in: query
          required: true
          description: Número máximo de resultados para retornar
          example: 10
          schema:
            type: integer
            maximum: 20
            minimum: 1
        - name: offset
          in: query
          description: Número de resultados que serão pulados na busca
          example: 60
          schema:
            type: integer
            maximum: 10000
            minimum: 0
        - name: sort
          in: query
          description: Forma de ordenação
          example: asc:concorrencia
          schema:
            type: string
            pattern: ^(asc|desc):(concorrencia|cursoNome|disciplinaNome)$
      requestBody:
        required: true
        description: Dias e horários para filtrar
        content:
          application/json:
            schema:
              type: object
              required:
                - filter
              properties:
                filter:
                  type: object
                  required:
                    - startTimestampMin
                    - endTimestampMin
                    - days
                  properties:
                    startTimestampMin:
                      type: integer
                      minimum: 1
                      maximum: 1440
                      example: 500
                    endTimestampMin:
                      example: 1000
                      type: integer
                      minimum: 1
                      maximum: 1440
                    days:
                      type: array
                      example: ["segunda", "terça"]
                      items:
                        type: string
                        pattern: ^(segunda|terça|quarta|quinta|sexta|sábado)$
                        maxItems: 168
      responses:
        "200":
          description: Resultados da busca
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Hit"
                maxLength: 20
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Hit:
      required:
        - codigo
        - curso
        - disciplina
        - horarios
      properties:
        codigo:
          type: string
          example: "1"
        curso:
          type: object
          properties:
            nome:
              type: string
              example: "Engenharia da Computação (Diurno)"
            codigo:
              type: string
              example: "FO05"
        disciplina:
          type: object
          properties:
            nome:
              type: string
              example: "EQUACÕES DIFERENCIAIS ORDINÁRIAS"
            codigo:
              type: string
              example: "IEM141"
        horarios:
          type: array
          items:
            type: object
            properties:
              dias:
                type: array
                items:
                  type: string
                  example: "Terça-feira"
              inicio:
                type: string
                example: "08:00"
                pattern: ^[0-9]{1,2}:[0-9]{1,2}$
              termino:
                type: string
                example: "10:00"
                pattern: ^[0-9]{1,2}:[0-9]{1,2}$
        concorrencia:
          type: number
          format: float
          description: relação de candidatos por vaga
          example: 0.75
    Error:
      required:
        - message
      properties:
        message:
          type: string
